### ISSUE TITLE
tritempor.py

### ISSUE THREAD

**Issue by ddzovo** [RascalGdd/TriTemp-OR#3]
In tritempor.py,line 28:self.encode_features = np.load(r"D:\DD\STIP_or\llava-med-emb.npy"),This appears to be your local file

**Comment by RascalGdd** [comment]
sorry, will update soon!

**Comment by RascalGdd** [comment]
Please download it from this link: https://gocuhk-my.sharepoint.com/:u:/g/personal/jialunpei_cuhk_edu_hk/EdXHUO0c52lGoDggXx10Pr8BTCJOwNCWw8_PWW7bxONRjA?e=v278nd
